Id: VideoLAN.VLC
Version: 3.0.10
Name: VLC media player
Publisher: VideoLAN
License: GNU General Public License Version 2
LicenseUrl: https://www.videolan.org/developers/vlc/COPYING
MinOSVersion: 5.1.2600.0
AppMoniker: VLC
Tags: "Media, media player, player, video, playback, vlc"
Description: A free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
Homepage: https://www.videolan.org/vlc/
Installers:
  - Arch: x64
    Url: http://download.videolan.org/pub/videolan/vlc/3.0.10/win64/vlc-3.0.10-win64.msi
    Sha256: B15A8B8BBF0027542AFE060CD00C6105D34A311A7E06DB028B62BB500B3DDD8E
    InstallerType: msi
